In [1]:
import pandas as pd
import numpy as np

In [2]:
emp_data=pd.read_csv(r"D:\Project\Employee_data.csv")

In [3]:
emp_data

,Unnamed: 0,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,0,Douglas,Male,8/6/1993,12:42 PM,97308.0,6.945,True,Marketing
1,1,Thomas,Male,3/31/1996,6:53 AM,61933.0,4.170,True,NaN
2,2,Maria,Female,4/23/1993,11:17 AM,130590.0,11.858,False,Finance
3,3,Jerry,Male,3/4/2005,1:00 PM,138705.0,9.340,True,Finance
4,4,Larry,Male,1/24/1998,4:47 PM,101004.0,1.389,True,Client Services
...,...,...,...,...,...,...,...,...,...
995,995,Henry,NaN,11/23/2014,6:09 AM,132483.0,16.655,False,Distribution
996,996,Phillip,Male,1/31/1984,6:30 AM,42392.0,19.675,False,Finance
997,997,Russell,Male,5/20/2013,12:39 PM,96914.0,1.421,False,Product
998,998,Larry,Male,4/20/2013,4:45 PM,60500.0,11.985,False,Business Development
999,999,Albert,Male,5/15/2012,6:24 PM,129949.0,10.169,True,Sales

In [4]:
#sales_data_orders.groupby("channel").aggregate({"revenue":"sum"})
emp_data.groupby("First Name").aggregate({"Salary":"count"},{"Salary":"mean"},{"Salary":"median"},{"Salary":"mode"})

            Salary
First Name
Aaron            4
Adam             4
Alan             3
Albert           6
Alice            8
...            ...
Walter           5
Wanda            2
Wayne            4
William          3
Willie           5

[200 rows x 1 columns]

In [5]:
summary=pd.Series({
    "count":emp_data["Salary"].count(),
    "mean":emp_data["Salary"].mean(),
    "median":emp_data["Salary"].median(),
    "mode": emp_data["Salary"].mode().iloc[0]
})

In [6]:
print(summary)

count       973.000000
mean      90700.946557
median    90370.000000
mode      86676.000000
dtype: float64

In [7]:
emp_data.dtypes

Unnamed: 0             int64
First Name               str
Gender                   str
Start Date               str
Last Login Time          str
Salary               float64
Bonus %              float64
Senior Management     object
Team                     str
dtype: object

In [8]:
emp_data.shape

(1000, 9)

In [9]:
rows, columns= emp_data.shape
print("Rows: ", rows)
print("Columns: ",columns)

Rows:  1000
Columns:  9

In [10]:
emp_data.isna().sum()

Unnamed: 0             0
First Name            67
Gender               145
Start Date             0
Last Login Time        0
Salary                27
Bonus %                0
Senior Management     67
Team                  43
dtype: int64

In [11]:
null_columns=emp_data.columns[emp_data.isnull().any()]
print(null_columns)

Index(['First Name', 'Gender', 'Salary', 'Senior Management', 'Team'], dtype='str')

In [12]:
null_columns

Index(['First Name', 'Gender', 'Salary', 'Senior Management', 'Team'], dtype='str')

In [13]:
null_cols=emp_data.select_dtypes(exclude="number").columns

In [14]:
print(null_cols)

Index(['First Name', 'Gender', 'Start Date', 'Last Login Time',
       'Senior Management', 'Team'],
      dtype='str')

In [20]:
#num_cols=emp_data.select_dtypes(include='number').columns
result=[]
col='Salary'

result.append({
    'Column': col,
    'Count': emp_data[col].count(),
    'Mean': emp_data[col].mean(),
    'Median': emp_data[col].median(),
    'Mode': emp_data[col].mode()[0]
})

summary=pd.DataFrame(result)
print(summary)

   Column  Count          Mean   Median     Mode
0  Salary    973  90700.946557  90370.0  86676.0

In [21]:
data_types=pd.DataFrame({
    'Column Name':emp_data.columns,
    'Data Type':emp_data.dtypes.values
})
print(data_types)

         Column Name Data Type
0         Unnamed: 0     int64
1         First Name       str
2             Gender       str
3         Start Date       str
4    Last Login Time       str
5             Salary   float64
6            Bonus %   float64
7  Senior Management    object
8               Team       str

In [22]:
rows=emp_data.shape[0]
columns=emp_data.shape[1]

print("Total Rows", rows)
print("Total columns", columns)

Total Rows 1000
Total columns 9

In [23]:
null_summary=pd.DataFrame({
    'Column Name':emp_data.columns,
    'Null Count':emp_data.isnull().sum().values
})

print(null_summary)

         Column Name  Null Count
0         Unnamed: 0           0
1         First Name          67
2             Gender         145
3         Start Date           0
4    Last Login Time           0
5             Salary          27
6            Bonus %           0
7  Senior Management          67
8               Team          43